export interface ThemeConfig {
  id: string;
  name: string;
  description?: string;
  primary: string;       // Primary accent / CTA color
  secondary: string;     // Secondary accent / gradient endpoint
  accent?: string;        // Accent / highlight color (e.g. coral flame)
  mode: "light" | "dark";
  bg?: string;
  card?: string;
  border?: string;
  text?: string;
  textMuted?: string;
}

export const THEME_PRESETS: ThemeConfig[] = [
  {
    id: "universal-teal",
    name: "🌿 Universal Pine & Mint (Current Theme)",
    description: "Official Theme: Deep Pine Teal with Mint Aqua background, 8% deeper green cards, and emerald-teal text gradient (Universal Gym Style).",
    primary: "#004D40",
    secondary: "#00796B",
    accent: "#059669",
    mode: "light",
    bg: "#E0F2F1",
    card: "#CEE8E3",
    border: "#9DCBC4",
    text: "#0C2822",
    textMuted: "#1F453E",
  },
  {
    id: "royal-blue",
    name: "Royal Tech Blue",
    description: "Modern high-tech clean palette with vibrant Azure highlights",
    primary: "#0070F3",
    secondary: "#0099FF",
    mode: "light",
    bg: "#F8FAFC",
    card: "#FFFFFF",
    border: "#E2E8F0",
    text: "#0F172A",
    textMuted: "#475569",
  },
  {
    id: "ocean-sapphire",
    name: "Ocean Sapphire",
    description: "Deep oceanic blue blended with bright sky cyan",
    primary: "#0284C7",
    secondary: "#38BDF8",
    mode: "light",
    bg: "#F8FAFC",
    card: "#FFFFFF",
    border: "#E2E8F0",
    text: "#0F172A",
    textMuted: "#475569",
  },
  {
    id: "electric-violet",
    name: "Electric Violet",
    description: "Sophisticated modern purple and vivid lavender gradients",
    primary: "#7C3AED",
    secondary: "#A855F7",
    mode: "light",
    bg: "#FAF5FF",
    card: "#FFFFFF",
    border: "#F3E8FF",
    text: "#1E1B4B",
    textMuted: "#581C87",
  },
  {
    id: "emerald-growth",
    name: "Emerald Growth",
    description: "Fresh corporate tech green with luminous mint accents",
    primary: "#059669",
    secondary: "#10B981",
    mode: "light",
    bg: "#F0FDF4",
    card: "#FFFFFF",
    border: "#DCFCE7",
    text: "#064E3B",
    textMuted: "#166534",
  },
  {
    id: "crimson-passion",
    name: "Crimson Modern",
    description: "Bold, energetic crimson red paired with rose accents",
    primary: "#E11D48",
    secondary: "#FB7185",
    mode: "light",
    bg: "#FFF1F2",
    card: "#FFFFFF",
    border: "#FFE4E6",
    text: "#881337",
    textMuted: "#9F1239",
  },
  {
    id: "sunset-amber",
    name: "Sunset Amber",
    description: "Warm golden amber with vibrant citrus energy",
    primary: "#EA580C",
    secondary: "#F59E0B",
    mode: "light",
    bg: "#FFFBEB",
    card: "#FFFFFF",
    border: "#FEF3C7",
    text: "#78350F",
    textMuted: "#92400E",
  },
  {
    id: "midnight-indigo",
    name: "Midnight Indigo",
    description: "Deep enterprise indigo with neon ultraviolet flair",
    primary: "#4F46E5",
    secondary: "#818CF8",
    mode: "light",
    bg: "#EEF2FF",
    card: "#FFFFFF",
    border: "#E0E7FF",
    text: "#312E81",
    textMuted: "#3730A3",
  },
  {
    id: "matrix-teal",
    name: "Matrix Teal",
    description: "Clean modern medical and fintech cyan-teal combination",
    primary: "#0D9488",
    secondary: "#06B6D4",
    mode: "light",
    bg: "#F0FDFA",
    card: "#FFFFFF",
    border: "#CCFBF1",
    text: "#134E4A",
    textMuted: "#115E59",
  },
  {
    id: "rose-quartz",
    name: "Rose Quartz",
    description: "Luxe magenta and strawberry quartz aesthetic",
    primary: "#DB2777",
    secondary: "#F472B6",
    mode: "light",
    bg: "#FDF2F8",
    card: "#FFFFFF",
    border: "#FCE7F3",
    text: "#831843",
    textMuted: "#9D174D",
  },
  {
    id: "slate-minimal",
    name: "Slate Minimalist",
    description: "Architectural monochrome slate & graphite contrast",
    primary: "#0F172A",
    secondary: "#475569",
    mode: "light",
    bg: "#F8FAFC",
    card: "#FFFFFF",
    border: "#E2E8F0",
    text: "#0F172A",
    textMuted: "#334155",
  },
  {
    id: "cyber-dark",
    name: "Cyber Dark (Night Mode)",
    description: "Deep obsidian dark mode with electric cyan & neon blue",
    primary: "#00E5FF",
    secondary: "#3B82F6",
    mode: "dark",
    bg: "#0B0F19",
    card: "#111827",
    border: "#1F2937",
    text: "#F9FAFB",
    textMuted: "#9CA3AF",
  },
  {
    id: "solar-orange",
    name: "Solar Orange",
    description: "Vibrant energetic orange paired with golden amber highlights",
    primary: "#FF6B00",
    secondary: "#F59E0B",
    mode: "light",
    bg: "#FFF7ED",
    card: "#FFFFFF",
    border: "#FFEDD5",
    text: "#7C2D12",
    textMuted: "#9A3412",
  },
  {
    id: "ember",
    name: "🔥 Ember Tech",
    description: "Sultry dark IT theme — Burnt Peach meets Light Red with Dark Gold accents. Energetic, bold & professional.",
    primary: "#FF6B47",    // Burnt Peach / Coral
    secondary: "#FF3D5A",  // Hot Light Red
    mode: "dark",
    bg: "#120A07",         // Deep charcoal ember
    card: "#1C1008",       // Warm dark card
    border: "#2E1A0E",     // Warm brown border
    text: "#FFF5F0",       // Warm white
    textMuted: "#C4937A",  // Muted peach-sand
  },
];
